2019-04-07 14:57:21,600 INFO     setup_logging done
2019-04-07 14:57:31,683 ERROR    Traceback (most recent call last):
2019-04-07 14:57:31,684 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 240, in advertise_service
2019-04-07 14:57:31,686 ERROR    protocols)
2019-04-07 14:57:31,687 ERROR    _bluetooth
2019-04-07 14:57:31,687 ERROR    .
2019-04-07 14:57:31,688 ERROR    error
2019-04-07 14:57:31,689 ERROR    :
2019-04-07 14:57:31,689 ERROR    (2, 'No such file or directory')
2019-04-07 14:57:31,690 ERROR    
During handling of the above exception, another exception occurred:
2019-04-07 14:57:31,690 ERROR    Traceback (most recent call last):
2019-04-07 14:57:31,691 ERROR      File "uus.py", line 207, in <module>
2019-04-07 14:57:31,693 ERROR    main()
2019-04-07 14:57:31,694 ERROR      File "uus.py", line 139, in main
2019-04-07 14:57:31,695 ERROR    profiles=[SERIAL_PORT_PROFILE])
2019-04-07 14:57:31,696 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 242, in advertise_service
2019-04-07 14:57:31,698 ERROR    raise BluetoothError (str (e))
2019-04-07 14:57:31,699 ERROR    bluetooth.btcommon
2019-04-07 14:57:31,699 ERROR    .
2019-04-07 14:57:31,700 ERROR    BluetoothError
2019-04-07 14:57:31,700 ERROR    :
2019-04-07 14:57:31,701 ERROR    (2, 'No such file or directory')
2019-04-07 14:57:31,702 ERROR    Exception ignored in:
2019-04-07 14:57:31,703 ERROR    <__main__.LoggerHelper object at 0x759663d0>
2019-04-07 14:57:31,704 ERROR    AttributeError
2019-04-07 14:57:31,705 ERROR    :
2019-04-07 14:57:31,705 ERROR    'LoggerHelper' object has no attribute 'flush'
2019-04-07 14:57:48,582 INFO     setup_logging done
2019-04-07 14:57:58,661 ERROR    Traceback (most recent call last):
2019-04-07 14:57:58,662 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 240, in advertise_service
2019-04-07 14:57:58,665 ERROR    protocols)
2019-04-07 14:57:58,666 ERROR    _bluetooth
2019-04-07 14:57:58,667 ERROR    .
2019-04-07 14:57:58,667 ERROR    error
2019-04-07 14:57:58,668 ERROR    :
2019-04-07 14:57:58,669 ERROR    (2, 'No such file or directory')
2019-04-07 14:57:58,669 ERROR    
During handling of the above exception, another exception occurred:
2019-04-07 14:57:58,670 ERROR    Traceback (most recent call last):
2019-04-07 14:57:58,671 ERROR      File "uus.py", line 207, in <module>
2019-04-07 14:57:58,673 ERROR    main()
2019-04-07 14:57:58,673 ERROR      File "uus.py", line 139, in main
2019-04-07 14:57:58,675 ERROR    profiles=[SERIAL_PORT_PROFILE])
2019-04-07 14:57:58,676 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 242, in advertise_service
2019-04-07 14:57:58,678 ERROR    raise BluetoothError (str (e))
2019-04-07 14:57:58,679 ERROR    bluetooth.btcommon
2019-04-07 14:57:58,680 ERROR    .
2019-04-07 14:57:58,680 ERROR    BluetoothError
2019-04-07 14:57:58,681 ERROR    :
2019-04-07 14:57:58,681 ERROR    (2, 'No such file or directory')
2019-04-07 14:57:58,683 ERROR    Exception ignored in:
2019-04-07 14:57:58,685 ERROR    <__main__.LoggerHelper object at 0x759283f0>
2019-04-07 14:57:58,685 ERROR    AttributeError
2019-04-07 14:57:58,686 ERROR    :
2019-04-07 14:57:58,686 ERROR    'LoggerHelper' object has no attribute 'flush'
2019-04-07 14:59:32,205 INFO     setup_logging done
2019-04-07 14:59:42,284 ERROR    Traceback (most recent call last):
2019-04-07 14:59:42,286 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 240, in advertise_service
2019-04-07 14:59:42,288 ERROR    protocols)
2019-04-07 14:59:42,290 ERROR    _bluetooth
2019-04-07 14:59:42,290 ERROR    .
2019-04-07 14:59:42,291 ERROR    error
2019-04-07 14:59:42,292 ERROR    :
2019-04-07 14:59:42,293 ERROR    (2, 'No such file or directory')
2019-04-07 14:59:42,293 ERROR    
During handling of the above exception, another exception occurred:
2019-04-07 14:59:42,294 ERROR    Traceback (most recent call last):
2019-04-07 14:59:42,295 ERROR      File "uus.py", line 207, in <module>
2019-04-07 14:59:42,297 ERROR    main()
2019-04-07 14:59:42,298 ERROR      File "uus.py", line 139, in main
2019-04-07 14:59:42,300 ERROR    profiles=[SERIAL_PORT_PROFILE])
2019-04-07 14:59:42,301 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 242, in advertise_service
2019-04-07 14:59:42,303 ERROR    raise BluetoothError (str (e))
2019-04-07 14:59:42,304 ERROR    bluetooth.btcommon
2019-04-07 14:59:42,305 ERROR    .
2019-04-07 14:59:42,305 ERROR    BluetoothError
2019-04-07 14:59:42,306 ERROR    :
2019-04-07 14:59:42,307 ERROR    (2, 'No such file or directory')
2019-04-07 14:59:42,308 ERROR    Exception ignored in:
2019-04-07 14:59:42,309 ERROR    <__main__.LoggerHelper object at 0x759a9350>
2019-04-07 14:59:42,310 ERROR    AttributeError
2019-04-07 14:59:42,311 ERROR    :
2019-04-07 14:59:42,311 ERROR    'LoggerHelper' object has no attribute 'flush'
2019-04-07 15:06:44,926 INFO     setup_logging done
2019-04-07 15:06:55,011 ERROR    Traceback (most recent call last):
2019-04-07 15:06:55,012 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 240, in advertise_service
2019-04-07 15:06:55,015 ERROR    protocols)
2019-04-07 15:06:55,016 ERROR    _bluetooth
2019-04-07 15:06:55,017 ERROR    .
2019-04-07 15:06:55,018 ERROR    error
2019-04-07 15:06:55,018 ERROR    :
2019-04-07 15:06:55,019 ERROR    (2, 'No such file or directory')
2019-04-07 15:06:55,020 ERROR    
During handling of the above exception, another exception occurred:
2019-04-07 15:06:55,020 ERROR    Traceback (most recent call last):
2019-04-07 15:06:55,021 ERROR      File "uus.py", line 207, in <module>
2019-04-07 15:06:55,023 ERROR    main()
2019-04-07 15:06:55,024 ERROR      File "uus.py", line 139, in main
2019-04-07 15:06:55,026 ERROR    profiles=[SERIAL_PORT_PROFILE])
2019-04-07 15:06:55,026 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 242, in advertise_service
2019-04-07 15:06:55,029 ERROR    raise BluetoothError (str (e))
2019-04-07 15:06:55,029 ERROR    bluetooth.btcommon
2019-04-07 15:06:55,030 ERROR    .
2019-04-07 15:06:55,031 ERROR    BluetoothError
2019-04-07 15:06:55,031 ERROR    :
2019-04-07 15:06:55,032 ERROR    (2, 'No such file or directory')
2019-04-07 15:06:55,033 ERROR    Exception ignored in:
2019-04-07 15:06:55,035 ERROR    <__main__.LoggerHelper object at 0x7598a3f0>
2019-04-07 15:06:55,035 ERROR    AttributeError
2019-04-07 15:06:55,036 ERROR    :
2019-04-07 15:06:55,037 ERROR    'LoggerHelper' object has no attribute 'flush'
2019-04-07 15:22:24,113 INFO     setup_logging done
2019-04-07 15:22:34,196 ERROR    Traceback (most recent call last):
2019-04-07 15:22:34,197 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 240, in advertise_service
2019-04-07 15:22:34,199 ERROR    protocols)
2019-04-07 15:22:34,200 ERROR    _bluetooth
2019-04-07 15:22:34,201 ERROR    .
2019-04-07 15:22:34,202 ERROR    error
2019-04-07 15:22:34,202 ERROR    :
2019-04-07 15:22:34,203 ERROR    (2, 'No such file or directory')
2019-04-07 15:22:34,204 ERROR    
During handling of the above exception, another exception occurred:
2019-04-07 15:22:34,204 ERROR    Traceback (most recent call last):
2019-04-07 15:22:34,205 ERROR      File "uus.py", line 207, in <module>
2019-04-07 15:22:34,207 ERROR    main()
2019-04-07 15:22:34,208 ERROR      File "uus.py", line 139, in main
2019-04-07 15:22:34,209 ERROR    profiles=[SERIAL_PORT_PROFILE])
2019-04-07 15:22:34,210 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 242, in advertise_service
2019-04-07 15:22:34,212 ERROR    raise BluetoothError (str (e))
2019-04-07 15:22:34,213 ERROR    bluetooth.btcommon
2019-04-07 15:22:34,214 ERROR    .
2019-04-07 15:22:34,215 ERROR    BluetoothError
2019-04-07 15:22:34,215 ERROR    :
2019-04-07 15:22:34,216 ERROR    (2, 'No such file or directory')
2019-04-07 15:22:34,217 ERROR    Exception ignored in:
2019-04-07 15:22:34,219 ERROR    <__main__.LoggerHelper object at 0x759ae330>
2019-04-07 15:22:34,219 ERROR    AttributeError
2019-04-07 15:22:34,220 ERROR    :
2019-04-07 15:22:34,220 ERROR    'LoggerHelper' object has no attribute 'flush'
2019-04-07 15:36:08,555 INFO     setup_logging done
2019-04-07 15:36:18,644 ERROR    Traceback (most recent call last):
2019-04-07 15:36:18,645 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 240, in advertise_service
2019-04-07 15:36:18,648 ERROR    protocols)
2019-04-07 15:36:18,648 ERROR    _bluetooth
2019-04-07 15:36:18,649 ERROR    .
2019-04-07 15:36:18,650 ERROR    error
2019-04-07 15:36:18,650 ERROR    :
2019-04-07 15:36:18,651 ERROR    (2, 'No such file or directory')
2019-04-07 15:36:18,652 ERROR    
During handling of the above exception, another exception occurred:
2019-04-07 15:36:18,652 ERROR    Traceback (most recent call last):
2019-04-07 15:36:18,653 ERROR      File "uus.py", line 207, in <module>
2019-04-07 15:36:18,655 ERROR    main()
2019-04-07 15:36:18,656 ERROR      File "uus.py", line 139, in main
2019-04-07 15:36:18,658 ERROR    profiles=[SERIAL_PORT_PROFILE])
2019-04-07 15:36:18,659 ERROR      File "/usr/local/lib/python3.5/dist-packages/bluetooth/bluez.py", line 242, in advertise_service
2019-04-07 15:36:18,661 ERROR    raise BluetoothError (str (e))
2019-04-07 15:36:18,662 ERROR    bluetooth.btcommon
2019-04-07 15:36:18,663 ERROR    .
2019-04-07 15:36:18,664 ERROR    BluetoothError
2019-04-07 15:36:18,664 ERROR    :
2019-04-07 15:36:18,665 ERROR    (2, 'No such file or directory')
2019-04-07 15:36:18,666 ERROR    Exception ignored in:
2019-04-07 15:36:18,668 ERROR    <__main__.LoggerHelper object at 0x759a6350>
2019-04-07 15:36:18,669 ERROR    AttributeError
2019-04-07 15:36:18,670 ERROR    :
2019-04-07 15:36:18,670 ERROR    'LoggerHelper' object has no attribute 'flush'
